### ISSUE TITLE
METEOR_SETTINGS required to run dev?

### ISSUE THREAD

**Issue by rdickert** [meteor-velocity/velocity-website#26]
Pulled the latest and wanted to troubleshoot. Running `meteor` locally:

```
W20150422-08:01:58.207(-6)? (STDERR) Error: --settings or METEOR_SETTINGS required.
W20150422-08:01:58.207(-6)? (STDERR)     at Object._.extend.setDefaults (packages/ogourment:settings/settings.js:13:1)
W20150422-08:01:58.207(-6)? (STDERR)     at _ (packages/xolvio:md-blog/server/blog-server.js:5:1)
W20150422-08:01:58.207(-6)? (STDERR)     at _ (packages/xolvio:md-blog/server/blog-server.js:123:1)
```

@samhatoum I think you'll know what's going on - feel free to put an action back on me if I might be missing something.

**Comment by samhatoum** [comment]
you just need to supply `meteor --settings settings.json`

**Comment by alanning** [comment]
Please see PR https://github.com/meteor-velocity/velocity-website/pull/27
